### ISSUE TITLE
[Gitlab] - Caching issue

### ISSUE THREAD

**Issue by a-chartier** [veepee-oss/terustry#1]
First, Thanks for this fantastic lightweight registry system. 

It seems like there might be some sort of cache issue when using Gitlab as the provider backend - I am getting ` no
│ available releases match the given constraints`  after a new release has been published

However this is corrected once i restart the application, I have left it sit for a number of hours and it still seems to report the same error.

The console show now errors

**Comment by rockyluke** [comment]
This has been fixed by @fcassin. Could you confirm ?

Thanks for your report 🙏

**Comment by fcassin** [comment]
Thanks for the report.

I have tried to reproduce the issue, unsuccessfully.
I created a pull request, updating a few dependencies and adding `WARN` logs when a request fails and causes the cache to fallback to a previous response.

I do not have the necessary rights to merge it at the moment, we will look into it.

If you're still encountering the same behaviour with this new version, could you please tell us about the constraints you're using when attempting to fetch a provider? I assumed you were looking for the latest new release.

The cache mechanism should keep the latest valid response for 10 minutes, after which it should perform a new request. Unless the request fails (which should trigger a `WARN` message), the cache should be refreshed and include any new version released in the meantime.

**Comment by a-chartier** [comment]
@fcassin @rockyluke 

Thanks for the update this will be helpful for trying to track down what's happening.  In this situation it was the latest but I was actually grabbing it specific version number.

I will give this a shot today and duplicate this too see what happens.

**Comment by a-chartier** [comment]
So I think this kind of explains it, in my situation we may end up pushing out new providers fairly quickly since they can be dynamically generated 

So it feasible that we push out  multiple releases within that 10 minute window. It seems like if it fails to find the entry in the cache it doesn't query Gitlab to check to see if it has a new release. 

I think ideally what would happen in this situation is that if it's a cache miss it will send the request to Gitlab/Github. This could also make sense as a configurable parameter

To test this out I did a 

`terraform init -upgrade`  -> Pinned at version `0.0.9`

I then generated a new provider version `0.0.10` which was fully released in Gitlab and reporting through the API 

I then bumped my TF version constraint to `0.0.10`

![image](https://github.com/user-attachments/assets/54b7b2b6-5daf-42ec-a364-e3ccc8e41b79)

and received the following error 

```
no available releases match the given constraints 0.0.10
```

I left it at that for  a while ( longer then 10 minutes) and once that cache timer you mentioned was up I was able to pull `0.0.10`

```
- Installing provier-name v0.0.10...
```

**Comment by fcassin** [comment]
Thanks for the additional information!

In this scenario, Terustry cannot know that a new version was released. It would then currently return an outdated versions list, which would result in the Terraform error message.

To work around this issue, I have changed the internal caching implementation to allow for the creation of a new cache invalidation route.

Documentation is available here:
https://github.com/veepee-oss/terustry?tab=readme-ov-file#caching

A new release was tagged:
https://github.com/veepee-oss/terustry/releases/tag/0.1.0

Details of the changes are available here:
https://github.com/veepee-oss/terustry/pull/3

I hope this will solve your issue.

**Comment by a-chartier** [comment]
This looks perfect, I will give this a try today.

Thank you very much for figuring out a solution for this

**Comment by a-chartier** [comment]
Sorry for the late response. This solution works as expected.

Thanks for this great project and for adding this in.

**Comment by fcassin** [comment]
Thanks for the feedback, I will now close the issue.
